name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    # --- ДОДАВАННЯ МАТРИЧНОЇ СТРАТЕГІЇ ---
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start LocalStack
        run: |
          docker compose up -d
          echo "Waiting for LocalStack..."
          sleep 10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave pytest-mock coverage pylint

      - name: Run pylint
        run: pylint --fail-under 7 app/eshop.py

      - name: Run Unit Tests (Lab 2)
        run: python -m unittest tests/test_unit.py

      - name: Run BDD Tests (Lab 1)
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          behave

      - name: Run Integration Tests & Coverage (Lab 3)
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/test_integration.py -v
          coverage run -m pytest tests/
          coverage report -m

      - name: Teardown Docker
        if: always()
        run: docker compose down